#! /bin/sh

sxhkd & bspc monitor -d      ♬     # I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true



#--------------------------------Window Rules-------------------------------
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Nemo desktop='^4' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Code desktop='^3' follow=on
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a Oblogout state=fullscreen 
bspc rule -a Deezer desktop='^6' follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Gimp desktop='^7' follow=on
bspc rule -a Oomox desktop='^7' follow=on
#---------------------------------------------------------------------------

#-------------------------------Inicialização-------------------------------
compton &
xfce4-power-manager &
numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
~/.config/polybar/launch.sh &
flameshot &
wal -R &
#---------------------------------------------------------------------------